"""correcao3

Revision ID: 39d5cf3adb46
Revises: 67d62746b69d
Create Date: 2022-07-31 21:24:20.878428

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39d5cf3adb46'
down_revision = '67d62746b69d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
