"""correcao2

Revision ID: 67d62746b69d
Revises: 7d627afc67fa
Create Date: 2022-07-31 21:22:02.324055

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67d62746b69d'
down_revision = '7d627afc67fa'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
