"""correcao4

Revision ID: 6b9baa6eecdb
Revises: 39d5cf3adb46
Create Date: 2022-07-31 21:26:53.400586

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b9baa6eecdb'
down_revision = '39d5cf3adb46'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
