"""correcao

Revision ID: 75075b5795b4
Revises: f6135e988c7a
Create Date: 2022-07-31 21:09:19.088231

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '75075b5795b4'
down_revision = 'f6135e988c7a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ImportacaoRealizada',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('data_transacao', sa.DateTime(), nullable=True),
    sa.Column('data_importacao', sa.DateTime(), nullable=True),
    sa.Column('id_user', sa.Integer(), nullable=True),
    sa.Column('id_transaçoes', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_transaçoes'], ['transaçoes.id'], ),
    sa.ForeignKeyConstraint(['id_user'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('importacao_realizada')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('importacao_realizada',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('data_transacao', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('data_importacao', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('id_user', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('id_transaçoes', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['id_transaçoes'], ['transaçoes.id'], name='importacao_realizada_id_transaçoes_fkey'),
    sa.ForeignKeyConstraint(['id_user'], ['users.id'], name='importacao_realizada_id_user_fkey'),
    sa.PrimaryKeyConstraint('id', name='importacao_realizada_pkey')
    )
    op.drop_table('ImportacaoRealizada')
    # ### end Alembic commands ###
