"""correcao

Revision ID: ed4a4056bb3c
Revises: 75075b5795b4
Create Date: 2022-07-31 21:17:27.539662

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed4a4056bb3c'
down_revision = '75075b5795b4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
