"""change in table user

Revision ID: f6135e988c7a
Revises: 83fcd9780dbf
Create Date: 2022-07-24 19:51:20.053646

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f6135e988c7a'
down_revision = '83fcd9780dbf'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
